# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rlnmmYl7IDMr2rMJEr8DM-a8lB-Emf9W
"""

import jax.numpy as jnp
from jax import grad, jit, vmap
from jax import random
import time
key = random.PRNGKey(0)
x = random.normal(key, (10,))
print(x)

size = 3000
x = random.normal(key, (size, size), dtype=jnp.float32)

# %timeit jnp.dot(x, x.T).block_until_ready()
sum = 0
for i in range(100):
  start = time.time()
  jnp.dot(x, x.T).block_until_ready()  # runs on the GPU
  end = time.time()
  sum += end - start
print(sum/100)